export interface SkillEntry {
  slug: string
  name: string
  description: string
  category: 'operations' | 'engineering' | 'content' | 'strategy' | 'personal' | 'community'
  defaultAgent: string
  tags: string[]
  complexity: 'simple' | 'moderate' | 'advanced'
}

export const SKILLS: SkillEntry[] = [
  // Operations (Maya)
  {
    slug: 'daily-review',
    name: 'Daily Review',
    description: 'Run a structured daily check-in: process inbox, review calendar, set top 3 priorities, and sync progress to your task board.',
    category: 'operations',
    defaultAgent: 'maya',
    tags: ['routine', 'planning', 'gtd'],
    complexity: 'moderate',
  },
  {
    slug: 'inbox-processing',
    name: 'Inbox Processing',
    description: 'Process messages from Telegram, email, or Slack using GTD methodology. Classify each item as action, reference, or trash.',
    category: 'operations',
    defaultAgent: 'maya',
    tags: ['inbox', 'gtd', 'automation'],
    complexity: 'moderate',
  },
  {
    slug: 'weekly-review',
    name: 'Weekly Review',
    description: 'Comprehensive weekly review: check OKR progress, review completed tasks, plan next week, flag blocked items.',
    category: 'operations',
    defaultAgent: 'maya',
    tags: ['review', 'planning', 'okrs'],
    complexity: 'advanced',
  },
  {
    slug: 'meeting-prep',
    name: 'Meeting Prep',
    description: 'Prepare for upcoming meetings: gather context from past notes, draft agenda items, set objectives.',
    category: 'operations',
    defaultAgent: 'maya',
    tags: ['meetings', 'preparation'],
    complexity: 'simple',
  },
  // Engineering (Viktor)
  {
    slug: 'code-review',
    name: 'Code Review',
    description: 'Review pull requests for code quality, security issues, and architectural alignment. Provide actionable feedback.',
    category: 'engineering',
    defaultAgent: 'viktor',
    tags: ['code', 'quality', 'review'],
    complexity: 'moderate',
  },
  {
    slug: 'deploy',
    name: 'Deploy',
    description: 'Run deployment pipeline: build, test, deploy to staging or production. Monitor for errors post-deploy.',
    category: 'engineering',
    defaultAgent: 'viktor',
    tags: ['ci-cd', 'deployment', 'monitoring'],
    complexity: 'advanced',
  },
  {
    slug: 'tech-debt-audit',
    name: 'Tech Debt Audit',
    description: 'Scan codebase for technical debt: outdated dependencies, duplicated code, missing tests, and security vulnerabilities.',
    category: 'engineering',
    defaultAgent: 'viktor',
    tags: ['tech-debt', 'audit', 'maintenance'],
    complexity: 'advanced',
  },
  {
    slug: 'bug-triage',
    name: 'Bug Triage',
    description: 'Analyze bug reports, reproduce issues, identify root causes, and either fix directly or create detailed issue tickets.',
    category: 'engineering',
    defaultAgent: 'viktor',
    tags: ['bugs', 'debugging', 'issues'],
    complexity: 'moderate',
  },
  // Content (Luna)
  {
    slug: 'blog-post',
    name: 'Blog Post',
    description: 'Write a full blog post: research topic, draft outline, write content, add SEO metadata, and prepare for publishing.',
    category: 'content',
    defaultAgent: 'luna',
    tags: ['writing', 'blog', 'seo'],
    complexity: 'moderate',
  },
  {
    slug: 'social-media',
    name: 'Social Media Post',
    description: 'Create platform-specific social media content: write copy, suggest images, schedule posts across channels.',
    category: 'content',
    defaultAgent: 'luna',
    tags: ['social', 'marketing', 'content'],
    complexity: 'simple',
  },
  {
    slug: 'seo-audit',
    name: 'SEO Audit',
    description: 'Analyze site for SEO health: check meta tags, page speed, broken links, keyword coverage, and content gaps.',
    category: 'content',
    defaultAgent: 'luna',
    tags: ['seo', 'audit', 'optimization'],
    complexity: 'advanced',
  },
  {
    slug: 'content-calendar',
    name: 'Content Calendar',
    description: 'Plan a content calendar for the upcoming month: topics, formats, platforms, and publishing dates.',
    category: 'content',
    defaultAgent: 'luna',
    tags: ['planning', 'content', 'calendar'],
    complexity: 'moderate',
  },
  // Strategy (Marco)
  {
    slug: 'okr-review',
    name: 'OKR Review',
    description: 'Review quarterly OKRs: assess progress on key results, flag at-risk items, suggest adjustments.',
    category: 'strategy',
    defaultAgent: 'marco',
    tags: ['okrs', 'review', 'planning'],
    complexity: 'moderate',
  },
  {
    slug: 'market-research',
    name: 'Market Research',
    description: 'Research a market segment: identify competitors, analyze pricing, map customer segments, and size the opportunity.',
    category: 'strategy',
    defaultAgent: 'marco',
    tags: ['research', 'market', 'analysis'],
    complexity: 'advanced',
  },
  {
    slug: 'pricing-strategy',
    name: 'Pricing Strategy',
    description: 'Develop or refine pricing for a product: analyze willingness to pay, compare competitors, model revenue scenarios.',
    category: 'strategy',
    defaultAgent: 'marco',
    tags: ['pricing', 'revenue', 'strategy'],
    complexity: 'advanced',
  },
  {
    slug: 'competitor-analysis',
    name: 'Competitor Analysis',
    description: 'Deep-dive into a competitor: features, pricing, positioning, strengths, weaknesses, and differentiation opportunities.',
    category: 'strategy',
    defaultAgent: 'marco',
    tags: ['competitors', 'analysis', 'strategy'],
    complexity: 'moderate',
  },
  // Personal (Sage)
  {
    slug: 'check-in',
    name: 'Personal Check-in',
    description: 'Guided personal check-in: energy level, mood, stress factors, wins of the day, and what needs attention.',
    category: 'personal',
    defaultAgent: 'sage',
    tags: ['wellbeing', 'routine', 'reflection'],
    complexity: 'simple',
  },
  {
    slug: 'journal-prompt',
    name: 'Journal Prompt',
    description: 'Generate a personalized journal prompt based on recent activities, goals, and emotional patterns.',
    category: 'personal',
    defaultAgent: 'sage',
    tags: ['journaling', 'reflection', 'growth'],
    complexity: 'simple',
  },
  {
    slug: 'energy-audit',
    name: 'Energy Audit',
    description: 'Analyze your week for energy patterns: what activities drain vs energize you, and suggest schedule adjustments.',
    category: 'personal',
    defaultAgent: 'sage',
    tags: ['energy', 'audit', 'optimization'],
    complexity: 'moderate',
  },
  {
    slug: 'life-assessment',
    name: 'Life Assessment',
    description: 'Run a Level 10 Life assessment: rate 10 life areas, compare to previous scores, identify focus areas.',
    category: 'personal',
    defaultAgent: 'sage',
    tags: ['assessment', 'life-design', 'quarterly'],
    complexity: 'moderate',
  },
  // Community (Kai)
  {
    slug: 'contact-enrichment',
    name: 'Contact Enrichment',
    description: 'Research a new contact: find their LinkedIn, Instagram, recent work, mutual connections, and conversation starters.',
    category: 'community',
    defaultAgent: 'kai',
    tags: ['crm', 'research', 'networking'],
    complexity: 'simple',
  },
  {
    slug: 'follow-up',
    name: 'Follow-up',
    description: 'Generate personalized follow-up messages for contacts you met recently. Reference shared interests or discussed topics.',
    category: 'community',
    defaultAgent: 'kai',
    tags: ['crm', 'outreach', 'networking'],
    complexity: 'simple',
  },
  {
    slug: 'community-pulse',
    name: 'Community Pulse',
    description: 'Analyze community health: engagement metrics, active members, trending topics, and suggested actions.',
    category: 'community',
    defaultAgent: 'kai',
    tags: ['community', 'metrics', 'engagement'],
    complexity: 'moderate',
  },
  {
    slug: 'event-planning',
    name: 'Event Planning',
    description: 'Plan a community event: define format, create agenda, draft invitations, set up logistics.',
    category: 'community',
    defaultAgent: 'kai',
    tags: ['events', 'planning', 'community'],
    complexity: 'advanced',
  },
]
